### ISSUE TITLE
deadlinks can't find docs on windows

### ISSUE THREAD

**Issue by bugadani** [deadlinks/cargo-deadlinks#119]
```
❯ cargo deadlinks -V
0.6.1

❯ cargo deadlinks
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
warning: no directories were detected
```

**Comment by jyn514** [comment]
Can you link a project where this occurs? Or is it on any cargo project?

If you pass `--no-build`, does it fix the issue?

**Comment by bugadani** [comment]
With `--no-build` it works:

```
❯ cargo deadlinks --no-build  
warning: --no-build ignores `doc = false` and may have other bugs
Found invalid urls in ...
```

I experienced it with https://github.com/embedded-graphics/embedded-text, but I don't think the project matters.

**Comment by jyn514** [comment]
Hmm, this will be tricky to debug since I don't have a windows machine. This seems like cargo isn't giving as much information as it should about targets? If you run `cargo doc --no-deps --message-format=json-rendered-diagnostics | jq 'select(.reason == "compiler-artifact") | .filenames[]'`, what output does that give?

**Comment by jyn514** [comment]
Oh! This might be because I assumed `/` was the directory separator: https://github.com/deadlinks/cargo-deadlinks/blob/567c551bc7c7149fc2d8f734652522dde60d7308/src/bin/cargo-deadlinks.rs#L163
The `cargo` output would still be helpful to double check that's the issue, though.

**Comment by jyn514** [comment]
@bugadani can you try out https://github.com/jyn514/cargo-deadlinks/tree/windows and see if it fixes the issue?

**Comment by bugadani** [comment]
Yup, looks good, thanks! :)
