### ISSUE TITLE
Fragment errors are reported for redirect pages

### ISSUE THREAD

**Issue by bugadani** [deadlinks/cargo-deadlinks#120]
When a type is exported in a prelude, rustdoc sometimes generates a redirection page. Funny enough, sometimes the destination page is in the prelude module, but this issue is not about that.

deadlinks doesn't follow redirection pages and reports `Fragment #... at ... does not exist!` errors. An example of this can be found here: https://github.com/embedded-graphics/embedded-text/runs/1453160019?check_suite_focus=true - in this case the fragment exists at `embedded_graphics/prelude/trait.DrawTarget.html#associatedtype.Error`

**Comment by jyn514** [comment]
How can I reproduce this error? I tried checking out that branch and running `cargo deadlinks`, which gave me
```
Found invalid urls in struct.TextBox.html:
	Fragment #tymethod.translate_mut at /home/joshua/.local/lib/cargo/target/doc/embedded_text/struct.TextBox.html does not exist!
Found invalid urls in struct.StyledTextBox.html:
	Fragment #tymethod.translate_mut at /home/joshua/.local/lib/cargo/target/doc/embedded_text/struct.StyledTextBox.html does not exist!
```
Both of those errors seem to be correct, they're broken links generated by rustdoc (https://github.com/rust-lang/rust/issues/74222).

**Comment by bugadani** [comment]
Huh, I don't have the errors you have. Strange, I have this issue with the 11-24 nightly rustc, are you using something else? Locally I have the same output as I linked in CI - I did nothing more than checking out master and running `cargo deadlinks`.

**Comment by bugadani** [comment]
@jyn514

```
cargo doc
cargo deadlinks [--no-build]
```

is not equivalent to `cargo deadlinks`. The former reproduces my output, the latter gives me yours.

**Comment by jyn514** [comment]
@bugadani yes, `cargo deadlinks` passes --no-deps. That's the recommended way to use deadlinks, since otherwise you get link failures from your dependencies too.

**Comment by jyn514** [comment]
Ok I see, I can reproduce now.

This is tricky to fix in general, since it requires knowing whether arbitrary HTML/JS will redirect to another page, independent of HTTP status codes. Fortunately it doesn't need to work in general, it only needs to work for the pages rustdoc generates, which look like this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="refresh" content="0;URL=../../embedded_graphics/prelude/trait.DrawTarget.html">
</head>
<body>
    <p>Redirecting to <a href="../../embedded_graphics/prelude/trait.DrawTarget.html">../../embedded_graphics/prelude/trait.DrawTarget.html</a>...</p>
    <script>location.replace("../../embedded_graphics/prelude/trait.DrawTarget.html" + location.search + location.hash);</script>
</body>
</html>
```

I think a sufficient workaround is to look for `<meta http-equiv=refresh content="URL=xxx">` and follow the redirect if so.
