### ISSUE TITLE
Test working_http_check::works failed

### ISSUE THREAD

**Issue by gkobeaga** [deadlinks/cargo-deadlinks#158]
The test fails because the are some issues while loading the page w3.org. It might be related with the incident [Redirecting to https on all of www.w3.org](https://status.w3.org/incidents/j1gjbnnd4rkk). I am reporting the issue just to be aware of the failed test, it can be closed once the page is again operation.

Log:
```
running 2 tests
test working_http_check::forbid_checking ... ok
test working_http_check::works ... FAILED

failures:

---- working_http_check::works stdout ----
thread 'working_http_check::works' panicked at 'Unexpected failure.
code-1
stderr=```" Documenting working_http_check v0.1.0 (/home/gkobeaga/src/cargo-deadlinks/tests/working_http_check)\n    Finished dev [unoptimized + debuginfo] target(s) in 0.27s\n"```
command=`"/home/gkobeaga/src/cargo-deadlinks/target/debug/cargo-deadlinks" "deadlinks" "--check-http"`
code=1
stdout="Found invalid urls in fn.foo.html:\n\tError fetching https://tinyurl.com/rnxcavf: Connection Failed: Connection reset by peer (os error 104)\n"
stderr=" Documenting working_http_check v0.1.0 (/home/gkobeaga/src/cargo-deadlinks/tests/working_http_check)\n    Finished dev [unoptimized + debuginfo] target(s) in 0.27s\n"
', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jyn514** [comment]
Thanks for the report! I can't replicate this locally. Unfortunately this test depends on external websites, which are inherently unreliable. I can change it to a host that I think is more reliable, like https://httpstat.us/, but we don't actually have a guarantee that site has better uptime, and it also doesn't help with weird requirements like "support sites that block the `HEAD` method".

Are you still running into this trouble? or was it a one-time issue?

**Comment by gkobeaga** [comment]
w3.org is up and the test is passing now
