### ISSUE TITLE
Shorten paths

### ISSUE THREAD

**Issue by KillTheMule** [deadlinks/cargo-deadlinks#19]
Output in my case is like this:

> Checking doc page at /mnt/data/pips/Devel/neovim/nvimpam/target/doc/nvimpam_lib/index.html
> Linked file at path /mnt/data/pips/Devel/neovim/nvimpam/target/doc/handler/struct.NeovimHandler.html do

This is kind of unwieldy, considering my cwd is `/mnt/data/pips/Devel/neovim/nvimpam/`, and I've given `target/doc/nvimpam_lib` as the `--dir` argument. Shortening the paths with the information available would make the output much more readable.

Thanks anyways, very nice tool.

**Comment by hobofan** [comment]
Yeah, makes sense! I'd be open for PRs.

To implement the future you'd have to drag a config containing the root path through all the check functions, which would also enable some of the other open feature requests. I'd also like to retain the printing of the full path when the debug flag is activated, to make sure that the search path is working correctly.
