### ISSUE TITLE
Error on the crate with a custom bin and lib

### ISSUE THREAD

**Issue by RazrFalcon** [deadlinks/cargo-deadlinks#21]
[The project](https://github.com/RazrFalcon/svgcleaner) itself.

```
% cargo deadlinks 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

It's probably due to custom bin/lib names.

**Comment by dhardy** [comment]
I now have a similar error with the rand lib (not sure why; it worked before):
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Better diagnostics would help a lot.

**Comment by hobofan** [comment]
Yeah, I don't think this is due to custom bin and lib, as I can not reproduce it. I think the error in the initial comment was due to `cargo doc` not being run before.

I'll try to change it to a better error message!

**Comment by hobofan** [comment]
A better error message is landing with #33.

While implementing it I also found out that even though the custom bin/lib name didn't cause the error in the case of svgcleaner, that problem can actually occur when it differs from the cargo project name 😅

**Comment by jyn514** [comment]
> While implementing it I also found out that even though the custom bin/lib name didn't cause the error in the case of svgcleaner, that problem can actually occur when it differs from the cargo project name 😅

This was fun to solve :) I have a fix in https://github.com/deadlinks/cargo-deadlinks/pull/68 - for it to work, it has to look at _all_ targets, not just the binary or library, but both. @RazrFalcon is that the behavior you'd expect? The alternative is find a way to set a 'primary' target somehow which sounds tricky.

**Comment by RazrFalcon** [comment]
@jyn514 I guess. That was long time ago. I was simply surprised by the panic.

**Comment by jyn514** [comment]
I see. The panic was also solved a while ago, in https://github.com/deadlinks/cargo-deadlinks/pull/33.

I don't expect #68 to break anything (it does strictly more work than before) so I'm going to go ahead with merging it, but let me know if you have any suggestions :)
