### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by pravic** [deadlinks/cargo-deadlinks#24]
`cargo-deadlinks` uses `cargo-edit` 0.1 which uses `curl-sys` 0.1 that uses `pkgconfig` which is not an option on Windows. However, the [cargo-edit](https://crates.io/crates/cargo-edit) is now 0.3 and now it works fine on this OS. 

Any chance to update on it? There are some errors if I just bump the dependency, so it needs to be checked by eye.

**Comment by hobofan** [comment]
Sorry, wrong issue number! 🙈

**Comment by hobofan** [comment]
`cargo_edit` has been replaced with `cargo_metadata` in 096dbc0, which should resolve this issue.

Should be released in `0.4.0`. Please reopen otherwise!
