### ISSUE TITLE
Publish 0.4 version on crates.io?

### ISSUE THREAD

**Issue by NikVolf** [deadlinks/cargo-deadlinks#25]
Current 0.3 version fails to compile on latest nightly and has rather outdated dependencies

**Comment by orium** [comment]
I'm also interested in this.  Is is possible to get a new release?

**Comment by hobofan** [comment]
The main thing that was blocking me from releasing was the behaviour of the http checking. Once I resolve #42, with a bit more added tests around that, `0.4.0` should be ready to be released (I'm giving the cautious target of end of the week).

**Comment by hobofan** [comment]
Version `0.4.0` has been published 🎉 !

It still has rather outdated dependencies though, see #46 for that.
