### ISSUE TITLE
Provide pre-built binaries compatible with install.sh

### ISSUE THREAD

**Issue by epage** [deadlinks/cargo-deadlinks#26]
I'd like to include this in my CI.  I could use `cargo install` but then it either slows down my CI or I have to deal with caching.

Ideally, I could pull in a pre-built version using [install.sh](https://github.com/japaric/trust/blob/master/ci/install.sh)

**Comment by dhardy** [comment]
Yes please. `cargo install` is over 11 minutes in Travis and I have issues using a cache (it grows to the point that workers timeout while cloning the cache).

**Comment by jyn514** [comment]
Added in 0.4.2: https://github.com/deadlinks/cargo-deadlinks/releases/tag/0.4.2. There are binaries available for linux, windows, and macOS.
