### ISSUE TITLE
Update to Rust Edition 2018

### ISSUE THREAD

**Issue by hobofan** [deadlinks/cargo-deadlinks#31]
I'd like to update this to Rust edition 2018, but I have the slight suspicion that this might break a small amount of projects that are building for a fixed Rust version below 1.31.

The update should only be done once #26 has been addressed, and we can provide an easy alternative install method for those projects.

**Comment by jyn514** [comment]
>  I have the slight suspicion that this might break a small amount of projects that are building for a fixed Rust version below 1.31.

It's now 2 years after the 2018 edition release, so I think this will be pretty rare. I have automatic deployments almost working though, so it doesn't hurt to wait.
