### ISSUE TITLE
Tracking intra-rustdoc links

### ISSUE THREAD

**Issue by hobofan** [deadlinks/cargo-deadlinks#35]
https://github.com/rust-lang/rust/issues/43466

Looks like the current status is that it's nightly-only for now.

Related to comment I previously made: https://github.com/deadlinks/cargo-deadlinks/issues/14#issuecomment-366798377

**Comment by jyn514** [comment]
Intra-doc links will be stable in 1.48, which releases in 5 weeks.

@hobofan what was this intended to track? Is there a change you wanted to make to deadlinks when intra-doc links are stabilized?

**Comment by hobofan** [comment]
I think mostly what I said in https://github.com/deadlinks/cargo-deadlinks/issues/14#issuecomment-366798377 : Once it lands on stable provide a hint to use the new intra-rustdoc link syntax.

**Comment by jyn514** [comment]
Gotcha. I think I'd rather have this as a rustdoc link than in cargo-deadlinks. Also, rustdoc can still generate broken links without warning (https://github.com/rust-lang/rust/pull/77971) so deadlinks would still be useful after intra-doc links are stable.
