### ISSUE TITLE
Provide a `deadlinks` crate

### ISSUE THREAD

**Issue by Marwes** [deadlinks/cargo-deadlinks#47]
I'd be interested in using `cargo-deadlinks` as a crate to test some html documentation I generate. Is this something you'd accept if I made a PR for it?

**Comment by hobofan** [comment]
Yes, that would be much appreciated! :)

**Comment by hobofan** [comment]
I'll reopen this, as I think it would be good to have a `deadlinks` crate that complements the `cargo-deadlinks` crate (that doesn't have any cargo dependencies) in the future. Might make sense to have that in a separate repository though.

**Comment by Marwes** [comment]
Cargo workspaces work great for that. Thought about putting things in a separate crate but didn't want to complicate the release process for you.

**Comment by hobofan** [comment]
Yeah, for now workspaces are probably good. Long-term vision was (at some point where I had more time for the project) that it would be usable from multiple languages, tools, and there I think having one cargo-agnositc repo that's focused on bindings would be good, but for now that's overkill.

I would accept a PR for workspaces 😇

**Comment by jyn514** [comment]
I think this doesn't need a full `deadlinks` crate, just a separate `deadlinks` and `cargo-deadlinks` binary. Cargo allows having multiple binaries in the same package, I'll take a look at that.
