### ISSUE TITLE
Maintenance status of cargo-deadlinks

### ISSUE THREAD

**Issue by jyn514** [deadlinks/cargo-deadlinks#58]
It looks like this repository hasn't seen activity in about a year and a half. There are a lot of open issues I'd like to see fixed, but PRs aren't being reviewed so I don't see much point in writing the fixes.

@hobofan are you still interested in maintaining this crate? If not, I'm interested in maintaining it myself.

**Comment by hobofan** [comment]
Thanks for reaching out! I don't really have the bandwidth right now to maintain the project and I also don't really use it myself anymore, so it's probably time to let go 😅

@jyn514 I've added you as an owner to the organization. Have fun! 😄 

I'd also recommend @Marwes as a co-maintainer if they are interested in that.

**Comment by jyn514** [comment]
@hobofan thank you so much! I'll make sure to take care of it :)

@marwes are you interested in being a maintainer?

**Comment by Marwes** [comment]
Sorry, no ,I have enough repositories I for which I am a passive maintainer on :)
