### ISSUE TITLE
cargo-deadlinks 0.4.2 tries to find docs for examples marked as `cdylib`

### ISSUE THREAD

**Issue by notdijon** [deadlinks/cargo-deadlinks#83]
**Reproduction steps**

`git clone https://github.com/notdijon/hexavalent && cd hexavalent && cargo doc && cargo deadlinks`

**Expected output**

no output, success

**Actual output**

```
Could not find directory "/tmp/hexavalent/target/doc/simple".

Please run `cargo doc` before running `cargo deadlinks`.
```

**Notes**

This doesn't happen with cargo-deadlinks 0.4.1.

My repo has an example at `examples/simple.rs`, which I think is what it's looking for.

Alternatively if there's some flag I should be passing to `cargo doc` to make it document examples, that's also valid, although nothing in `cargo doc --help` seems to do so.

**Comment by jyn514** [comment]
This happens because your example is marked as `cdylib`, not `bin` or `lib`, and cargo-deadlinks assumes that anything that's not a binary is a library. I think I could avoid this by always ignoring `kind: example` regardless of the crate type.
