### ISSUE TITLE
Should respect target with doc=false when determining docs to check

### ISSUE THREAD

**Issue by ayazhafiz** [deadlinks/cargo-deadlinks#99]
Currently [`doc = false`](https://doc.rust-lang.org/cargo/commands/cargo-doc.html#target-selection) in a package's manifest is not respected when determining whether a target's docs should be checked:

https://github.com/deadlinks/cargo-deadlinks/blob/fd46075e299c1810a820f9eb96cb65ba893de950/src/main.rs#L133-L150

Furthermore, `cargo metadata` does not seem to report the value of the `doc` setting for targets, so this is probably an upstream bug to cargo folks first.

**Comment by jyn514** [comment]
It looks like you can get whether `doc` is set with `doctest`:

```
$ cat Cargo.toml
... snip ...
[lib]
doc = false
$ cargo metadata | jq '.packages[] | select(.source == null) | .targets[].doctest'
warning: please specify `--format-version` flag explicitly to avoid compatibility problems
false
```

**Comment by jyn514** [comment]
Actually, I think `doctest` can completely replace the current hacky logic :tada:

**Comment by ayazhafiz** [comment]
I'm not sure that is correct, see https://github.com/rust-lang/cargo/blob/0d8cab42f6ea3300ffec35677c4474e81208e16e/src/cargo/core/manifest.rs#L284. It seems that `doctest` does not correspond to whether `doc = true` is set.

**Comment by jyn514** [comment]
Ah hmm, you're right - `doctest` is always `false` for binaries, even if they will be documented.
```
$ cargo metadata | jq '.packages[] | select(.source == null) | .targets[] | select(.crate_types | contains(["bin"])) | { kind, crate_types, name, doctest }'
{
  "kind": [
    "bin"
  ],
  "crate_types": [
    "bin"
  ],
  "name": "exonum-timestamping",
  "doctest": false
}
```

**Comment by ayazhafiz** [comment]
I have a patch to add `doc` to the output of metadata, just waiting for all these tests to pass...

**Comment by ayazhafiz** [comment]
re 

> Ah hmm, you're right - `doctest` is always `false` for binaries, even if they will be documented.

yep, because of https://github.com/rust-lang/cargo/blob/0d8cab42f6ea3300ffec35677c4474e81208e16e/src/cargo/core/manifest.rs#L768-L775
